version: '2.1'

services:
  edge: # front end
    build:
      context: .
    volumes:
      - "./edge.conf:/usr/local/openresty/nginx/conf/nginx.conf"
      - "./src/:/lua/src/"
    depends_on:
      - admin
      - ingest
    links:
      - admin
      - ingest
    ports:
      - "8080:8080"
      - "9090:9090"

  ingest: # back end
    build:
      context: .
      dockerfile: Dockerfile.ingest
    volumes:
      - "./ingest.conf:/config/nginx.conf"
    ports:
      - "1935:1935"

  origin: # simulating a live transmission
    image: jrottenberg/ffmpeg:4.1
    entrypoint: bash
    command: "/scripts/ffmpeg_colorbar.sh"
    volumes:
      - "./:/scripts"
    depends_on:
      - ingest
    links:
      - ingest

  admin:
    build: ./admin
    command: bash -c "./scripts/wait-for.sh db 3306 && rails db:migrate && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./admin:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=admin

  db:
    image: mysql:5.6
    volumes:
      - "./mysqldata:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=admin

  lint:
    command: bash -c "luacheck -q ."
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ".:/lua/"
    working_dir: "/lua"

